INSERT INTO ingredients(ing_name) VALUES ("Bok Choy");
INSERT INTO ingredients(ing_name) VALUES ("Snake Beans");
INSERT INTO ingredients(ing_name) VALUES ("Sorrel Leaves");
INSERT INTO ingredients(ing_name) VALUES ("Rocket Leaves");
INSERT INTO ingredients(ing_name) VALUES ("Drumstick");
INSERT INTO ingredients(ing_name) VALUES ("Cherry Tomatoes");
INSERT INTO ingredients(ing_name) VALUES ("Kaffir Lime");
INSERT INTO ingredients(ing_name) VALUES ("Plantain");
INSERT INTO ingredients(ing_name) VALUES ("Turnip");
INSERT INTO ingredients(ing_name) VALUES ("Sweet Potatoes");
INSERT INTO ingredients(ing_name) VALUES ("Round Gourd");
INSERT INTO ingredients(ing_name) VALUES ("Ridge Gourd");
INSERT INTO ingredients(ing_name) VALUES ("Pimiento");
INSERT INTO ingredients(ing_name) VALUES ("Spinach");
INSERT INTO ingredients(ing_name) VALUES ("Onion");
INSERT INTO ingredients(ing_name) VALUES ("Mustard Leaves");
INSERT INTO ingredients(ing_name) VALUES ("Mushroom");
INSERT INTO ingredients(ing_name) VALUES ("Radish");
INSERT INTO ingredients(ing_name) VALUES ("Shallots");
INSERT INTO ingredients(ing_name) VALUES ("Lettuce");
INSERT INTO ingredients(ing_name) VALUES ("Leek");
INSERT INTO ingredients(ing_name) VALUES ("Pumpkin");
INSERT INTO ingredients(ing_name) VALUES ("Yam");
INSERT INTO ingredients(ing_name) VALUES ("Jalapeno");
INSERT INTO ingredients(ing_name) VALUES ("Jackfruit");
INSERT INTO ingredients(ing_name) VALUES ("Horseradish");
INSERT INTO ingredients(ing_name) VALUES ("Spring Onion");
INSERT INTO ingredients(ing_name) VALUES ("Green Peas");
INSERT INTO ingredients(ing_name) VALUES ("Green Chillies");
INSERT INTO ingredients(ing_name) VALUES ("Cluster Beans");
INSERT INTO ingredients(ing_name) VALUES ("Gherkins");
INSERT INTO ingredients(ing_name) VALUES ("Garlic");
INSERT INTO ingredients(ing_name) VALUES ("French Beans");
INSERT INTO ingredients(ing_name) VALUES ("Fenugreek");
INSERT INTO ingredients(ing_name) VALUES ("Cucumber");
INSERT INTO ingredients(ing_name) VALUES ("Zucchini");
INSERT INTO ingredients(ing_name) VALUES ("Corn");
INSERT INTO ingredients(ing_name) VALUES ("Shiitake Mushroom");
INSERT INTO ingredients(ing_name) VALUES ("Celery");
INSERT INTO ingredients(ing_name) VALUES ("Cauliflower");
INSERT INTO ingredients(ing_name) VALUES ("Carrot");
INSERT INTO ingredients(ing_name) VALUES ("Capsicum");
INSERT INTO ingredients(ing_name) VALUES ("Capers");
INSERT INTO ingredients(ing_name) VALUES ("Broccoli");
INSERT INTO ingredients(ing_name) VALUES ("Broad Beans");
INSERT INTO ingredients(ing_name) VALUES ("Bottle Gourd");
INSERT INTO ingredients(ing_name) VALUES ("Bitter Gourd");
INSERT INTO ingredients(ing_name) VALUES ("Lady Finger");
INSERT INTO ingredients(ing_name) VALUES ("Lotus Stem");
INSERT INTO ingredients(ing_name) VALUES ("Bell Pepper");
INSERT INTO ingredients(ing_name) VALUES ("Beetroot");
INSERT INTO ingredients(ing_name) VALUES ("Pigweed");
INSERT INTO ingredients(ing_name) VALUES ("Cabbage");
INSERT INTO ingredients(ing_name) VALUES ("Bamboo Shoot");
INSERT INTO ingredients(ing_name) VALUES ("Baby Corn");
INSERT INTO ingredients(ing_name) VALUES ("Avocado");
INSERT INTO ingredients(ing_name) VALUES ("Eggplant");
INSERT INTO ingredients(ing_name) VALUES ("Asparagus");
INSERT INTO ingredients(ing_name) VALUES ("Ash Gourd");
INSERT INTO ingredients(ing_name) VALUES ("Artichoke");
INSERT INTO ingredients(ing_name) VALUES ("Colocasia");
INSERT INTO ingredients(ing_name) VALUES ("Potatoes");
INSERT INTO ingredients(ing_name) VALUES ("Ginger");
INSERT INTO ingredients(ing_name) VALUES ("Gruyere Cheese");
INSERT INTO ingredients(ing_name) VALUES ("Gouda Cheese");
INSERT INTO ingredients(ing_name) VALUES ("Feta Cheese");
INSERT INTO ingredients(ing_name) VALUES ("Milk");
INSERT INTO ingredients(ing_name) VALUES ("Brie Cheese");
INSERT INTO ingredients(ing_name) VALUES ("Cream Cheese");
INSERT INTO ingredients(ing_name) VALUES ("Ricotta Cheese");
INSERT INTO ingredients(ing_name) VALUES ("Parmesan Cheese");
INSERT INTO ingredients(ing_name) VALUES ("Blue Cheese");
INSERT INTO ingredients(ing_name) VALUES ("Cheddar Cheese");
INSERT INTO ingredients(ing_name) VALUES ("Mascarpone Cheese");
INSERT INTO ingredients(ing_name) VALUES ("Cream");
INSERT INTO ingredients(ing_name) VALUES ("Provolone Cheese");
INSERT INTO ingredients(ing_name) VALUES ("Mozzarella Cheese");
INSERT INTO ingredients(ing_name) VALUES ("Khoya");
INSERT INTO ingredients(ing_name) VALUES ("Hung Curd");
INSERT INTO ingredients(ing_name) VALUES ("Yogurt");
INSERT INTO ingredients(ing_name) VALUES ("Cottage Cheese");
INSERT INTO ingredients(ing_name) VALUES ("Condensed Milk");
INSERT INTO ingredients(ing_name) VALUES ("Clarified Butter");
INSERT INTO ingredients(ing_name) VALUES ("Buttermilk");
INSERT INTO ingredients(ing_name) VALUES ("Butter");
INSERT INTO ingredients(ing_name) VALUES ("Amaranth");
INSERT INTO ingredients(ing_name) VALUES ("Flour");
INSERT INTO ingredients(ing_name) VALUES ("Muesli");
INSERT INTO ingredients(ing_name) VALUES ("Oats");
INSERT INTO ingredients(ing_name) VALUES ("Jowar");
INSERT INTO ingredients(ing_name) VALUES ("Brown Rice");
INSERT INTO ingredients(ing_name) VALUES ("Arborio Rice");
INSERT INTO ingredients(ing_name) VALUES ("Water Chestnut flour");
INSERT INTO ingredients(ing_name) VALUES ("Barnyard Millet");
INSERT INTO ingredients(ing_name) VALUES ("Tapioca");
INSERT INTO ingredients(ing_name) VALUES ("Semolina");
INSERT INTO ingredients(ing_name) VALUES ("Ragi");
INSERT INTO ingredients(ing_name) VALUES ("Puffed Rice");
INSERT INTO ingredients(ing_name) VALUES ("Buckwheat");
INSERT INTO ingredients(ing_name) VALUES ("Kidney Beans");
INSERT INTO ingredients(ing_name) VALUES ("Whole Bengal Gram");
INSERT INTO ingredients(ing_name) VALUES ("Green Gram");
INSERT INTO ingredients(ing_name) VALUES ("All Purpose Flour");
INSERT INTO ingredients(ing_name) VALUES ("Whole Brown Lentils");
INSERT INTO ingredients(ing_name) VALUES ("Husked Black Gram");
INSERT INTO ingredients(ing_name) VALUES ("Husked Green Gram");
INSERT INTO ingredients(ing_name) VALUES ("Couscous");
INSERT INTO ingredients(ing_name) VALUES ("Cornmeal");
INSERT INTO ingredients(ing_name) VALUES ("Pressed Rice");
INSERT INTO ingredients(ing_name) VALUES ("Rice");
INSERT INTO ingredients(ing_name) VALUES ("Breadcrumbs");
INSERT INTO ingredients(ing_name) VALUES ("Bread");
INSERT INTO ingredients(ing_name) VALUES ("Black-eyed Beans");
INSERT INTO ingredients(ing_name) VALUES ("Black Gram");
INSERT INTO ingredients(ing_name) VALUES ("Black Beans");
INSERT INTO ingredients(ing_name) VALUES ("Gram flour");
INSERT INTO ingredients(ing_name) VALUES ("Bengal Gram (Split)");
INSERT INTO ingredients(ing_name) VALUES ("Chickpeas");
INSERT INTO ingredients(ing_name) VALUES ("Basmati Rice");
INSERT INTO ingredients(ing_name) VALUES ("Barley");
INSERT INTO ingredients(ing_name) VALUES ("Pearl Millet");
INSERT INTO ingredients(ing_name) VALUES ("Whole Wheat Flour");
INSERT INTO ingredients(ing_name) VALUES ("Pigeon Pea");
INSERT INTO ingredients(ing_name) VALUES ("Bean Sprouts");
INSERT INTO ingredients(ing_name) VALUES ("Coriander Powder");
INSERT INTO ingredients(ing_name) VALUES ("Chives");
INSERT INTO ingredients(ing_name) VALUES ("Galangal");
INSERT INTO ingredients(ing_name) VALUES ("Tulsi");
INSERT INTO ingredients(ing_name) VALUES ("Sage");
INSERT INTO ingredients(ing_name) VALUES ("Rosemary");
INSERT INTO ingredients(ing_name) VALUES ("Yellow Chillies");
INSERT INTO ingredients(ing_name) VALUES ("Oregano");
INSERT INTO ingredients(ing_name) VALUES ("Nasturtium");
INSERT INTO ingredients(ing_name) VALUES ("Salt");
INSERT INTO ingredients(ing_name) VALUES ("Mustard Powder");
INSERT INTO ingredients(ing_name) VALUES ("Paprika");
INSERT INTO ingredients(ing_name) VALUES ("Mint Leaves");
INSERT INTO ingredients(ing_name) VALUES ("Marjoram");
INSERT INTO ingredients(ing_name) VALUES ("Lemongrass");
INSERT INTO ingredients(ing_name) VALUES ("Red Chilli");
INSERT INTO ingredients(ing_name) VALUES ("Saffron");
INSERT INTO ingredients(ing_name) VALUES ("Dried Fenugreek Leaves");
INSERT INTO ingredients(ing_name) VALUES ("Kashmiri Mirch");
INSERT INTO ingredients(ing_name) VALUES ("Onion Seeds");
INSERT INTO ingredients(ing_name) VALUES ("Mace");
INSERT INTO ingredients(ing_name) VALUES ("Nutmeg");
INSERT INTO ingredients(ing_name) VALUES ("Herbs");
INSERT INTO ingredients(ing_name) VALUES ("Thyme");
INSERT INTO ingredients(ing_name) VALUES ("Turmeric");
INSERT INTO ingredients(ing_name) VALUES ("Garam Masala");
INSERT INTO ingredients(ing_name) VALUES ("Five Spice Powder");
INSERT INTO ingredients(ing_name) VALUES ("Fenugreek Seeds");
INSERT INTO ingredients(ing_name) VALUES ("Fennel");
INSERT INTO ingredients(ing_name) VALUES ("Green Cardamom");
INSERT INTO ingredients(ing_name) VALUES ("Dry Ginger Powder");
INSERT INTO ingredients(ing_name) VALUES ("Dill");
INSERT INTO ingredients(ing_name) VALUES ("Curry Leaves");
INSERT INTO ingredients(ing_name) VALUES ("Cumin Seeds");
INSERT INTO ingredients(ing_name) VALUES ("Coriander Seeds");
INSERT INTO ingredients(ing_name) VALUES ("Coriander Leaves");
INSERT INTO ingredients(ing_name) VALUES ("Cloves");
INSERT INTO ingredients(ing_name) VALUES ("Cinnamon");
INSERT INTO ingredients(ing_name) VALUES ("Star Anise");
INSERT INTO ingredients(ing_name) VALUES ("Cayenne Pepper");
INSERT INTO ingredients(ing_name) VALUES ("Caraway Seeds");
INSERT INTO ingredients(ing_name) VALUES ("Cajun Spices");
INSERT INTO ingredients(ing_name) VALUES ("Rock Salt");
INSERT INTO ingredients(ing_name) VALUES ("Black Pepper");
INSERT INTO ingredients(ing_name) VALUES ("Black Cumin");
INSERT INTO ingredients(ing_name) VALUES ("Bay Leaf");
INSERT INTO ingredients(ing_name) VALUES ("Basil");
INSERT INTO ingredients(ing_name) VALUES ("Black Cardamom");
INSERT INTO ingredients(ing_name) VALUES ("Asafoetida");
INSERT INTO ingredients(ing_name) VALUES ("Aniseed");
INSERT INTO ingredients(ing_name) VALUES ("Raw Mango Powder");
INSERT INTO ingredients(ing_name) VALUES ("Allspice");
INSERT INTO ingredients(ing_name) VALUES ("Carom Seeds");
INSERT INTO ingredients(ing_name) VALUES ("Parsley");
INSERT INTO ingredients(ing_name) VALUES ("Acacia");
INSERT INTO ingredients(ing_name) VALUES ("Beef");
INSERT INTO ingredients(ing_name) VALUES ("Grass Fed Chicken");
INSERT INTO ingredients(ing_name) VALUES ("Free Range Chicken");
INSERT INTO ingredients(ing_name) VALUES ("Organic Chicken");
INSERT INTO ingredients(ing_name) VALUES ("Turkey");
INSERT INTO ingredients(ing_name) VALUES ("Skinned Chicken");
INSERT INTO ingredients(ing_name) VALUES ("Pork");
INSERT INTO ingredients(ing_name) VALUES ("Partridge");
INSERT INTO ingredients(ing_name) VALUES ("Meat Stock");
INSERT INTO ingredients(ing_name) VALUES ("Keema");
INSERT INTO ingredients(ing_name) VALUES ("Mutton Liver");
INSERT INTO ingredients(ing_name) VALUES ("Ham");
INSERT INTO ingredients(ing_name) VALUES ("Kidney Meat");
INSERT INTO ingredients(ing_name) VALUES ("Crab");
INSERT INTO ingredients(ing_name) VALUES ("Chicken Stock");
INSERT INTO ingredients(ing_name) VALUES ("Chicken Liver");
INSERT INTO ingredients(ing_name) VALUES ("Chicken");
INSERT INTO ingredients(ing_name) VALUES ("Chops");
INSERT INTO ingredients(ing_name) VALUES ("Lamb Meat");
INSERT INTO ingredients(ing_name) VALUES ("Quail");
INSERT INTO ingredients(ing_name) VALUES ("Mutton");
INSERT INTO ingredients(ing_name) VALUES ("Bacon");
INSERT INTO ingredients(ing_name) VALUES ("Cranberry");
INSERT INTO ingredients(ing_name) VALUES ("Kiwi");
INSERT INTO ingredients(ing_name) VALUES ("Blueberries");
INSERT INTO ingredients(ing_name) VALUES ("Mango");
INSERT INTO ingredients(ing_name) VALUES ("Watermelon");
INSERT INTO ingredients(ing_name) VALUES ("Tomato");
INSERT INTO ingredients(ing_name) VALUES ("Strawberry");
INSERT INTO ingredients(ing_name) VALUES ("Water Chestnut");
INSERT INTO ingredients(ing_name) VALUES ("Papaya");
INSERT INTO ingredients(ing_name) VALUES ("Orange Rind");
INSERT INTO ingredients(ing_name) VALUES ("Orange");
INSERT INTO ingredients(ing_name) VALUES ("Olives");
INSERT INTO ingredients(ing_name) VALUES ("Pear");
INSERT INTO ingredients(ing_name) VALUES ("Sultana");
INSERT INTO ingredients(ing_name) VALUES ("Mulberry");
INSERT INTO ingredients(ing_name) VALUES ("Lychee");
INSERT INTO ingredients(ing_name) VALUES ("Lemon Juice");
INSERT INTO ingredients(ing_name) VALUES ("Lemon Rind");
INSERT INTO ingredients(ing_name) VALUES ("Lemon");
INSERT INTO ingredients(ing_name) VALUES ("Raisins");
INSERT INTO ingredients(ing_name) VALUES ("Jamun");
INSERT INTO ingredients(ing_name) VALUES ("Tamarind");
INSERT INTO ingredients(ing_name) VALUES ("Grapefruit");
INSERT INTO ingredients(ing_name) VALUES ("Indian Gooseberry");
INSERT INTO ingredients(ing_name) VALUES ("Dried Fruit");
INSERT INTO ingredients(ing_name) VALUES ("Dates");
INSERT INTO ingredients(ing_name) VALUES ("Custard Apple");
INSERT INTO ingredients(ing_name) VALUES ("Currant");
INSERT INTO ingredients(ing_name) VALUES ("Cooking Apples");
INSERT INTO ingredients(ing_name) VALUES ("Coconut");
INSERT INTO ingredients(ing_name) VALUES ("Cherry");
INSERT INTO ingredients(ing_name) VALUES ("Cape Gooseberry");
INSERT INTO ingredients(ing_name) VALUES ("Banana");
INSERT INTO ingredients(ing_name) VALUES ("Peach");
INSERT INTO ingredients(ing_name) VALUES ("Apricots");
INSERT INTO ingredients(ing_name) VALUES ("Apples");
INSERT INTO ingredients(ing_name) VALUES ("Figs");
INSERT INTO ingredients(ing_name) VALUES ("Grapes");
INSERT INTO ingredients(ing_name) VALUES ("Pomegranate");
INSERT INTO ingredients(ing_name) VALUES ("Pineapple");
INSERT INTO ingredients(ing_name) VALUES ("Guava");
INSERT INTO ingredients(ing_name) VALUES ("Plum");
INSERT INTO ingredients(ing_name) VALUES ("Shrimp");
INSERT INTO ingredients(ing_name) VALUES ("Tuna Fish");
INSERT INTO ingredients(ing_name) VALUES ("Shellfish");
INSERT INTO ingredients(ing_name) VALUES ("Shark");
INSERT INTO ingredients(ing_name) VALUES ("Hilsa");
INSERT INTO ingredients(ing_name) VALUES ("Sardines");
INSERT INTO ingredients(ing_name) VALUES ("Salmon");
INSERT INTO ingredients(ing_name) VALUES ("Prawns");
INSERT INTO ingredients(ing_name) VALUES ("Pomfret");
INSERT INTO ingredients(ing_name) VALUES ("Perch");
INSERT INTO ingredients(ing_name) VALUES ("Pearl spot");
INSERT INTO ingredients(ing_name) VALUES ("Mussels");
INSERT INTO ingredients(ing_name) VALUES ("Mullet");
INSERT INTO ingredients(ing_name) VALUES ("Squids");
INSERT INTO ingredients(ing_name) VALUES ("Haddock");
INSERT INTO ingredients(ing_name) VALUES ("Flounder");
INSERT INTO ingredients(ing_name) VALUES ("Fish Stock");
INSERT INTO ingredients(ing_name) VALUES ("Fish");
INSERT INTO ingredients(ing_name) VALUES ("Fish Fillet");
INSERT INTO ingredients(ing_name) VALUES ("Cuttle fish");
INSERT INTO ingredients(ing_name) VALUES ("Cod");
INSERT INTO ingredients(ing_name) VALUES ("Clams");
INSERT INTO ingredients(ing_name) VALUES ("Cat fish");
INSERT INTO ingredients(ing_name) VALUES ("Mackerel");
INSERT INTO ingredients(ing_name) VALUES ("Anchovies");
INSERT INTO ingredients(ing_name) VALUES ("Brown Sugar");
INSERT INTO ingredients(ing_name) VALUES ("Mishri");
INSERT INTO ingredients(ing_name) VALUES ("Icing Sugar");
INSERT INTO ingredients(ing_name) VALUES ("Honey");
INSERT INTO ingredients(ing_name) VALUES ("Jaggery");
INSERT INTO ingredients(ing_name) VALUES ("Golden Syrup");
INSERT INTO ingredients(ing_name) VALUES ("Sugar");
INSERT INTO ingredients(ing_name) VALUES ("Castor Sugar");
INSERT INTO ingredients(ing_name) VALUES ("Caramel");
INSERT INTO ingredients(ing_name) VALUES ("Cane Sugar");
INSERT INTO ingredients(ing_name) VALUES ("Canola Oil");
INSERT INTO ingredients(ing_name) VALUES ("Chia Seeds");
INSERT INTO ingredients(ing_name) VALUES ("Hazelnut");
INSERT INTO ingredients(ing_name) VALUES ("Pine Nuts");
INSERT INTO ingredients(ing_name) VALUES ("Mustard Oil");
INSERT INTO ingredients(ing_name) VALUES ("Sunflower Seeds");
INSERT INTO ingredients(ing_name) VALUES ("Sesame Oil");
INSERT INTO ingredients(ing_name) VALUES ("Pistachio");
INSERT INTO ingredients(ing_name) VALUES ("Olive Oil");
INSERT INTO ingredients(ing_name) VALUES ("Mustard Seeds");
INSERT INTO ingredients(ing_name) VALUES ("Poppy Seeds");
INSERT INTO ingredients(ing_name) VALUES ("Sesame Seeds");
INSERT INTO ingredients(ing_name) VALUES ("Peanuts");
INSERT INTO ingredients(ing_name) VALUES ("Chironji");
INSERT INTO ingredients(ing_name) VALUES ("Cashew Nuts");
INSERT INTO ingredients(ing_name) VALUES ("Blanched Almonds");
INSERT INTO ingredients(ing_name) VALUES ("Almonds");
INSERT INTO ingredients(ing_name) VALUES ("Walnuts");
INSERT INTO ingredients(ing_name) VALUES ("Almond Milk");
INSERT INTO ingredients(ing_name) VALUES ("Red Wine Vinegar");
INSERT INTO ingredients(ing_name) VALUES ("Red Wine");
INSERT INTO ingredients(ing_name) VALUES ("Margarine");
INSERT INTO ingredients(ing_name) VALUES ("Soy Milk");
INSERT INTO ingredients(ing_name) VALUES ("White Wine");
INSERT INTO ingredients(ing_name) VALUES ("Yeast");
INSERT INTO ingredients(ing_name) VALUES ("White Pepper");
INSERT INTO ingredients(ing_name) VALUES ("Rice Vinegar");
INSERT INTO ingredients(ing_name) VALUES ("Sea Salt");
INSERT INTO ingredients(ing_name) VALUES ("Hoisin Sauce");
INSERT INTO ingredients(ing_name) VALUES ("Malt Vinegar");
INSERT INTO ingredients(ing_name) VALUES ("Chocolate Chips");
INSERT INTO ingredients(ing_name) VALUES ("Quinoa");
INSERT INTO ingredients(ing_name) VALUES ("Rice Flour");
INSERT INTO ingredients(ing_name) VALUES ("Polenta");
INSERT INTO ingredients(ing_name) VALUES ("Oyster Sauce");
INSERT INTO ingredients(ing_name) VALUES ("Guchchi");
INSERT INTO ingredients(ing_name) VALUES ("Flat Noodles");
INSERT INTO ingredients(ing_name) VALUES ("Balsamic Vinegar");
INSERT INTO ingredients(ing_name) VALUES ("Coconut Oil");
INSERT INTO ingredients(ing_name) VALUES ("Barfi");
INSERT INTO ingredients(ing_name) VALUES ("Rice Noodles");
INSERT INTO ingredients(ing_name) VALUES ("Coffee");
INSERT INTO ingredients(ing_name) VALUES ("Beer");
INSERT INTO ingredients(ing_name) VALUES ("Chocolate");
INSERT INTO ingredients(ing_name) VALUES ("Sake");
INSERT INTO ingredients(ing_name) VALUES ("Vinaigrette");
INSERT INTO ingredients(ing_name) VALUES ("Vanilla Essence");
INSERT INTO ingredients(ing_name) VALUES ("Tortilla");
INSERT INTO ingredients(ing_name) VALUES ("Tomato Puree");
INSERT INTO ingredients(ing_name) VALUES ("Vegetable Oil");
INSERT INTO ingredients(ing_name) VALUES ("Tartaric Acid");
INSERT INTO ingredients(ing_name) VALUES ("Soya Sauce");
INSERT INTO ingredients(ing_name) VALUES ("Vinegar");
INSERT INTO ingredients(ing_name) VALUES ("Sharbat");
INSERT INTO ingredients(ing_name) VALUES ("Vermicelli");
INSERT INTO ingredients(ing_name) VALUES ("Sev");
INSERT INTO ingredients(ing_name) VALUES ("Rum");
INSERT INTO ingredients(ing_name) VALUES ("Roux");
INSERT INTO ingredients(ing_name) VALUES ("Petha");
INSERT INTO ingredients(ing_name) VALUES ("Pasta");
INSERT INTO ingredients(ing_name) VALUES ("Papad");
INSERT INTO ingredients(ing_name) VALUES ("Paan");
INSERT INTO ingredients(ing_name) VALUES ("Meringue");
INSERT INTO ingredients(ing_name) VALUES ("Mayonnaise");
INSERT INTO ingredients(ing_name) VALUES ("Melon Seeds");
INSERT INTO ingredients(ing_name) VALUES ("Makhana");
INSERT INTO ingredients(ing_name) VALUES ("Vetiver");
INSERT INTO ingredients(ing_name) VALUES ("Kewda");
INSERT INTO ingredients(ing_name) VALUES ("Jus");
INSERT INTO ingredients(ing_name) VALUES ("Jelly");
INSERT INTO ingredients(ing_name) VALUES ("Rose Water");
INSERT INTO ingredients(ing_name) VALUES ("Gold Leaves");
INSERT INTO ingredients(ing_name) VALUES ("Glycerine");
INSERT INTO ingredients(ing_name) VALUES ("Gelatin");
INSERT INTO ingredients(ing_name) VALUES ("Fish Sauce");
INSERT INTO ingredients(ing_name) VALUES ("Desiccated Coconut");
INSERT INTO ingredients(ing_name) VALUES ("Cranberry Sauce");
INSERT INTO ingredients(ing_name) VALUES ("Cornflour");
INSERT INTO ingredients(ing_name) VALUES ("Cognac");
INSERT INTO ingredients(ing_name) VALUES ("Coconut Water");
INSERT INTO ingredients(ing_name) VALUES ("Coconut Milk");
INSERT INTO ingredients(ing_name) VALUES ("Cocoa");
INSERT INTO ingredients(ing_name) VALUES ("Tea");
INSERT INTO ingredients(ing_name) VALUES ("Brown Sauce");
INSERT INTO ingredients(ing_name) VALUES ("Baking Soda");
INSERT INTO ingredients(ing_name) VALUES ("Tofu");
INSERT INTO ingredients(ing_name) VALUES ("Baking Powder");
INSERT INTO ingredients(ing_name) VALUES ("Arrowroot");
INSERT INTO ingredients(ing_name) VALUES ("Egg");
INSERT INTO ingredients(ing_name) VALUES ("Alum");
INSERT INTO ingredients(ing_name) VALUES ("Extra Virgin Olive Oil");
INSERT INTO ingredients(ing_name) VALUES ("Lamb Chops");
